# Generated by Django 3.2.19 on 2023-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_auto_20230531_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='id',
            new_name='id_news',
        ),
        migrations.AddField(
            model_name='news',
            name='comments_count',
            field=models.IntegerField(default=36135533),
            preserve_default=False,
        ),
    ]
