# Generated by Django 3.2.19 on 2023-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_auto_20230531_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='sitestr',
            field=models.CharField(default='youtube.com', max_length=200),
            preserve_default=False,
        ),
    ]
