# Generated by Django 3.2.19 on 2023-06-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0004_auto_20230601_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
    ]
